version: '3'
services:
  gs-config-server:
    image: gs-config-server:1.0-SNAPSHOT
    ports:
      - '8080:8080'
    networks:
      gs-network:
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5

  gs-catalog:
    image: gs-catalog:1.0-SNAPSHOT
    depends_on:
      - gs-config-server
      - gs-catalog-db
    ports:
      - '8081:8081'
    networks:
      gs-network:
    environment:
      CONFIG_SERVER_URL: "http://gs-config-server"
      GS_CATALOG_DB_URL: "jdbc:mysql://gs-catalog-db:3307/${GS_CATALOG_DB}"
      GS_CATALOG_DB_USERNAME: ${MYSQL_USER}
      GS_CATALOG_DB_PASSWORD: ${MYSQL_PASSWORD}

  gs-catalog-db:
    image: mysql
    environment:
      MYSQL_DATABASE: ${GS_CATALOG_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3307:3306'
    volumes:
      - gs-catalog-db-volume:/var/lib/mysql
    networks:
      gs-network:

networks:
  gs-network:

volumes:
  gs-catalog-db-volume:
